### ISSUE TITLE
Review parameters

### ISSUE THREAD

**Issue by jpadmin** [CiscoDevNet/appdynamics-ansible#70]
Hello Team,

I have been trying to use this roles to install appdynamics Machine agent but could see that some of the parameters are unnecessarily redefined causing issues to the installation.

Eg 1: the controller parameters in https://github.com/Appdynamics/appdynamics-ansible/blob/master/playbooks/vars/controller.yaml and  https://github.com/Appdynamics/appdynamics-ansible/blob/master/roles/common/defaults/main.yaml

Eg 2: the analytics settings in https://github.com/Appdynamics/appdynamics-ansible/blob/master/playbooks/machine.yaml and https://github.com/Appdynamics/appdynamics-ansible/blob/master/roles/common/defaults/main.yaml

Can you review it and make necessary changes so that we can directly use this repository for the installation.

**Comment by jpadmin** [comment]
Tagging @kyle-lt for better reach

**Comment by iogbole** [comment]
FYI @v-zhuravlev

**Comment by v-zhuravlev** [comment]
Hi @jpadmin , can you please tell me a bit more what is the issue exactly?

Playbooks are provided as quick examples how collection can be used, while roles are essential part of it. 

`common-role/defaults/main.yaml` is the place where some defaults that should work for most users can be stored (so, connection settings to SaaS analytics), while vars/controller.yaml file in the playbooks folder is here to give the users an idea how these settings can be redefined to work in their environment. 

Actually, controller/analytics defaults may be redefined not only in vars files but in many other places, depending on your preference. For instance, host_vars in inventory: 
https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable

**Comment by jpadmin** [comment]
Hi @v-zhuravlev , the problem lies exactly when some of the parameters are redefined as seen in [common/defaults/main.yml](https://github.com/Appdynamics/appdynamics-ansible/blob/master/roles/common/defaults/main.yaml), making us not use the playbooks effectively.

For instance, consider the following code segment in `common/defaults/main.yml`

> controller_port: "8090"
> controller_account_name: "customer1" # Please add this to your Vault

And when we set these parameters in our playbook file, only settings provided in [common/defaults/main.yml](https://github.com/Appdynamics/appdynamics-ansible/blob/master/roles/common/defaults/main.yaml) gets the precedence over our input values. And no matter whatever our controller port and accountname is, the automation consider the values only from the defaults mentioned in the common role.

Thanks!
John

**Comment by v-zhuravlev** [comment]
@jpadmin , role defaults should not get precedence, they are just 'defaults' and least default thing according ansible docs:

https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html#understanding-variable-precedence

So any playbook, role, or task variables you can define should win over defaults.

Can you please share the playbook file where you have this behaviour?

**Comment by v-zhuravlev** [comment]
@jpadmin  do you have the latest 21.4 version of the collection? there were some changes (variables moved from vars to defaults)

**Comment by jpadmin** [comment]
Thanks its sorted
